# Numpy를 알아보자!
넘파이란? - 수치해석용 파이썬 패키지

넘파는를 왜 사용할까?
- 파이썬 자체에는 배열 자료형이 없어서 넘파이를 사용하여 배열을 사용하기 위함.

배열을 왜 쓸까?
- 배열을 사용하면 백터화 연산을 통해 빠르게 수치계산을 할 수 있다.

리스트와 배열의 차이

1. 배열은 모든 원소가 같은 자료형 이어야 한다.
2. 원소의 갯수를 바꿀 수 없다.





넘파이 임포트 np 로 줄여서 사용

In [1]:
import numpy as np

버전확인

In [6]:
np.__version__

'1.23.0'

넘파이 배열생성

In [3]:
ar = np.array([0,1,2,3,4,5,6])

array([0, 1, 2, 3, 4, 5, 6])

In [4]:
type(ar)

numpy.ndarray

백터화 연산

In [5]:
ar*2

array([ 0,  2,  4,  6,  8, 10, 12])

In [8]:
ar> 5

array([False, False, False, False, False, False,  True])

2차원 행렬 만들기

In [9]:
c = np.array([[0,1,2],[3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
len(c)# 행의 갯수

2

In [11]:
len(c[0])# 열의 갯수

3

3차원 행렬 만들기

In [14]:
d =np.array([[[1,2,3,4],[4,5,6,7]],[[8,9,10,11],[11,12,13,14]]])
d

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [11, 12, 13, 14]]])

In [15]:
#깊이,행,열
len(d),len(d[0]),len(d[0][0])

(2, 2, 4)

배열의 차원과 크기 알아내기

In [18]:
d.ndim, d.shape

(3, (2, 2, 4))

배열 인덱싱

In [19]:
d[0]

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [22]:
d[0,0]

array([1, 2, 3, 4])

In [21]:
d[0,0,0]

1

In [25]:
d[:2,:2,:1]

array([[[ 1],
        [ 4]],

       [[ 8],
        [11]]])

조건을 사용한 배열 인덱싱

In [27]:
a = np.array([0,1,2,3,4,5,6])
idx = [True,False,True,False,True,False,True]
a[idx]

array([0, 2, 4, 6])

In [28]:
a%2

array([0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [29]:
a%2==0

array([ True, False,  True, False,  True, False,  True])

In [31]:
a[a%2]

array([0, 1, 0, 1, 0, 1, 0])

0만 원소로 가지는 배열 생성

In [32]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

1만 원소로 가지는 배열

In [33]:
np.ones(5)

array([1., 1., 1., 1., 1.])

다른 배열과 크기를 맞춰서 생성하고 싶을때

In [34]:
np.zeros_like(a, dtype= 'f') # a라는 배열 크기만큼 float형으로 배열을 만들어라.

array([0., 0., 0., 0., 0., 0., 0.], dtype=float32)

초기화를 하지않는 배열

In [37]:
np.empty((4,3))

array([[1.01636028e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.08221785e-312, 1.10593106e-046],
       [7.26960656e-043, 1.10655651e+165, 1.43402534e+161],
       [4.85184476e-033, 8.44630472e+169, 1.74652909e-076]])

arange 사용 하기

In [38]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [41]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [42]:
np.logspace(0.1,1,10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

전치 연산 -> T
- 배열의 행과 열을 바꾸는 작업

In [43]:
A = np.array([[1,2,3],[4,5,6]])

In [44]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

배열의 크기 변형

In [45]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

다차원 배열을 1차원 배열로 만들기

In [51]:
a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
a.ravel()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

브로드캐스팅 - 행렬이 같지 않은 배열의 연산시에 행렬의 자동으로 맞춰줌 

In [54]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [55]:
x+1

array([1, 2, 3, 4, 5])

차원축소, 정렬, 기술통계

In [59]:
x.sum(),x.min(),x.max(),x.argmin(),x.argmax(),x.mean(), x.std(),x.var(), x.all(),x.any()

(10, 0, 4, 0, 4, 2.0, 1.4142135623730951, 2.0, False, True)

In [61]:
x.sort()
x

array([0, 1, 2, 3, 4])

In [65]:
np.median(x)

2.0